@startuml useCase
left to right direction
actor Utente
actor Ospite
actor Cliente
actor Admin
actor "Server" as S

Utente --> Ospite
Utente --> Cliente
Utente --> Admin
Utente --> S

rectangle "Diagramma dei casi d'uso"{
  Ospite -- (Visualizza mappa)
  Ospite -- (Si registra)
  (Si registra) --> (Riceve tessera elettronica)

  Cliente -- (Visualizza mappa)
  Cliente -- (Visualizza riepiloghi)
  Cliente -- (Si autentica)
  Cliente -- (Noleggia bici)
  (Noleggia bici) --> (Usa tessera elettronica)
  Cliente -- (Consegna bici)

  rectangle "Monitoraggio servizio"{
    Admin -- (Stampe)
    (Stampe) --> (Operazione utenti)
    (Stampe) --> (Operazione stazioni)
    (Stampe) --> (Posizione bicicletta)
    (Stampe) --> (Biciclette non riconsegnate)
    (Stampe) --> (Biciclette in manutenzione)
    (Stampe) --> (Slot in manutenzione)

  }

  rectangle "Manutenzione servizio"{
    S -- (Inserimento bicicletta)
    S -- (Cancellazione bicicletta)
  }

  rectangle "Gesitone servizio"{
    S -- (Tariffazione servizio)
    S -- (Gestione mappa)
    S -- (Gestione utenti)
    S -- (Gestione smart card)
  }

}

@enduml